services:
  - type: web
    name: binance-futures-sniper-engine
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.12.0
